X=MsgBox("System starting error!",0+16,"Error 0x00010")
Set objNet = WScript.CreateObject("WScript.Network")
WScript.Echo "Wellcome " & objNet.ComputerName
X=MsgBox("The main applications cannot be started!",0+16,"Error 01x001101")
X=MsgBox("Firewall/antivirus error!",0+16,"Error 1101")
X=MsgBox("Firewall/antivirus has become inactive!",0+16,"Error 11001")
X=MsgBox("System error!",0+16,"Error 101")
X=MsgBox("Network error!",0+16,"Error 010")
X=MsgBox("Account error!",0+16,"Error 5849")
X=MsgBox("The verygoodfreeAV.exe started in the background!",0+64,"Started")
X=MsgBox("The NotVirus.exestarted in the background!",0+64,"Started")
X=MsgBox("You do not have enough permissions to use it!",0+16,"Error 1002")
X=MsgBox("Resending your data to the server!",0+64,"Resending...")
X=MsgBox("Updating all malware to the latest version!",0+32,"Updtaing...")
X=MsgBox("The Windows Defender.exe is not found!",0+16,"Error 0210")
X=MsgBox("The UpdateMalw.exe cannot be start!",0+16,"Error 0210")
X=MsgBox("The UnnamedRans.exe cannot be start!",0+16,"Error 0210")
X=MsgBox("System error!",0+16,"Error 101")
X=MsgBox("System error!",0+16,"Error 101")
X=MsgBox("System error!",0+16,"Error 101")
X=MsgBox("System error!",0+16,"Error 101")
X=MsgBox("You are not the owner, bye-bye!",0+48,"Error 01011")
Set objShell = WScript.CreateObject("WScript.Shell")
objShell.Run ("[shutdown.bat] " & WScript.ScriptFullName)